CREATE TABLE user_info(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT UNIQUE NOT NULL, 
    firstname VARCHAR(250),
    middlename VARCHAR(250),
    lastname VARCHAR(250),
    gender VARCHAR(1),
    phone VARCHAR(250),
    icon_url VARCHAR(400),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);